image:
  repository: ghcr.io/metal-stack/os-metal-extension
  tag: latest
  pullPolicy: Always

resources: {}

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false
  heartbeat: 
    renewIntervalSeconds: 30

leaderElection:
  resourceLock: leases

disableControllers: []
